from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    price = models.DecimalField(max_digits=10, decimal_places=2) # for NTD price this is not needed

class Order(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True, blank=True)
    order_number = models.IntegerField() # since the order id is already generated by django, this might not be needed
    total_price = models.IntegerField()
    created_time = models.DateTimeField(auto_now_add=True)
    products = models.ManyToManyField(Product, related_name='orders')